# Generated by Django 5.0.6 on 2025-08-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=100, unique=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("os", models.CharField(blank=True, default="", max_length=200)),
                ("cpu_model", models.CharField(blank=True, default="", max_length=200)),
                ("cores", models.IntegerField(default=0)),
                ("threads", models.IntegerField(default=0)),
                ("ram_total_gb", models.FloatField(default=0)),
                ("ram_used_gb", models.FloatField(default=0)),
                ("ram_available_gb", models.FloatField(default=0)),
                ("storage_total_gb", models.FloatField(default=0)),
                ("storage_used_gb", models.FloatField(default=0)),
                ("storage_free_gb", models.FloatField(default=0)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="monitor.computer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("ppid", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("cpu", models.FloatField()),
                ("mem_mb", models.FloatField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="monitor.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pid"],
                "indexes": [
                    models.Index(
                        fields=["pid", "ppid"], name="monitor_pro_pid_54e0f8_idx"
                    )
                ],
            },
        ),
    ]
